---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: prometheus-host
  namespace: observability
spec:
  hostname: prom-server.twistedlife.space
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-prom-server-ingress
  selector:
    matchLabels:
      hostname: prometheus
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: prom-alert-host
  namespace: observability
spec:
  hostname: prom-alert.twistedlife.space
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-prom-alert-ingress
  selector:
    matchLabels:
      hostname: alertmanager
