apiVersion: v2
name: kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    # renovate: registryUrl=https://grafana.github.io/helm-charts
    version: "0.53.1"
    repository: https://prometheus-community.github.io/helm-charts
