apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  project: twisted-infra-app
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    helm:
      valueFiles:
        - values.yaml
