apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: loki-helm-values
  namespace: observability
spec:
  encryptedData:
    values.yaml: AgC2GKrHcr5E+EMx7k2aPb5hNpE01m7piMmSoA+/vCGZebqQmMsAFoE1SlSzhgVyBWtzp1IFm8D2HdFBObk8mOxik+D1Xw4DhWen/h3qW6MfC0X+332+xaqEMXSzoNoxb4iEtcVdSonSHcj8KPS1O0bYSKWLEWU8boLezQARWJ7hX6xFwpS166Ga4lxeadjfzyehTXMHTn+b3d5X3idzEA1YMKc6UszzqYQIS4W7nNiFVedjRnzMxF9WHdnvZMVaulk6cUvM3i7RAprTWRXiRZF5Cwf2EeSfXH4bZHCkWVkisZLNnfgVg4GYq8++3uy1DJ+LWyeNoyMW+ZrApTZJ3PkqbG5oEnDQcBSKjR1q9PVSpmI2109aoytIHUNZJA0nyrIaQiRW6dchpjD3IpprsynqeeLd79KFy1MDr71dvSUm8cOa/SOAFBiRNKFbERkK35TRn1eDgAOKOPGxfTDTvrn+6hN973Gg41HvsgUtFCuVPcFiiIGkoQdVaWWbr4NvU0xzQw7Q/UOnzvfvaZaKR5KMBc5ODxxIyxnRaPt77HvhqL8viLHqy0EkSsTLPFqVU2wEZZ46SZy1TBru8KtvhoLUktu+u9zlEpjlg71lxLBGCyExMB7fCcC0HdMGHbKdPnZpbMXN2Y4dXyXplKqwVVfEcpa+NIJR7TmpPv7WiQKBFPV8FzfL1rI3kFACUQ+W0qiKXNeRM5RV26g7qTlJSjlgeSit0uPHD7xyIji+JhL9C0Mb+gdCkkKGqUpJiPsvu6MNBwDwxQXObIaz0wOjCZ08a64dqn1wYlWODHrh45FlDxWSgxM/6bdbuh3vDJgyoDWd6GaTybwrUO7ZdwpQGwlcMW40MuXOWJgtlL5VTlcjlR1fTY5BnPNn/T4qfCmD2e/8D0pJIf/4vuvFFv5FzEZ4wxXUYYZlCMM+O0nMOohokSnGVl0ZXlzguai8j9PoHRlvRoHotm6E+3F6vslTc7sVjT8isr2l4w7aXTDThKmD+HfYatdboeqM0tna/kgXV3t1UWWiapmN
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: loki-helm-values
      namespace: observability
