apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: twisted-infra-app
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    path: charts/loki-stack/
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
