apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-sc
  annotations: {}
  #    key: string
  labels: {}
#    key: string
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
#  key: string
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
__clone: true
