apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    email: syork@yorkserv.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: {}
        dns01:
          cloudflare:
            email: syork@yorkserv.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: syork@yorkserv.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: {}
        dns01:
          cloudflare:
            email: syork@yorkserv.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: kube-system
spec:
  secretName: acme-crt-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: twistedlife.space
  dnsNames:
    - twistedlife.space
    - "*.twistedlife.space"
    - "*.kube.twistedlife.space"
