apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-audiobooks-pv
  namespace: storage
spec:
  storageClassName: media-audiobooks
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "truenas.storage.twistedlife.space"
    path: "/mnt/Media/media/audiobooks"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-audiobooks-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-audiobooks
  resources:
    requests:
      storage: 1Mi
