apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-minio
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
    - host: s3.twistedlife.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-minio
                port:
                  number: 9000
  tls:
    - hosts:
        - minio.twistedlife.space
---
apiVersion: v1
kind: Service
metadata:
  name: external-minio
spec:
  ports:
    - name: minio
      port: 9000
  type: ExternalName
  externalName: s3.twistedlife.space
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-truenas
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
    - host: truenas.twistedlife.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-truenas
                port:
                  number: 443
  tls:
    - hosts:
        - truenas.twistedlife.space
---
apiVersion: v1
kind: Service
metadata:
  name: external-truenas
spec:
  ports:
    - name: https
      port: 443
  type: ExternalName
  externalName: truenas.twistedlife.space
