influxdb:
  image:
    repository: "influxdb"
    tag: "2.1.1-alpine"
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    size: 50Gi
    storageClass: csi-rbd-sc
  resources:
    requests:
      memory: 2000Mi
      cpu: 100m
    limits:
      memory: 4000Mi
  livenessProbe:
    timeoutSeconds: 10
  readinessProbe:
    timeoutSeconds: 10
  startupProbe:
    enabled: true
    failureThreshold: 10
    periodSeconds: 10
  podAnnotations:
    backup.velero.io/backup-volumes: influxdb-data
  tolerations:
    - key: "arm"
      operator: "Exists"
