---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
stringData:
  # Required for statically provisioned volumes
  userID: admin
  userKey: AQDxNKNhgSTNABAA7YkCzWWqTI04t7RVkwcXAg==
