apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: storage
spec:
  encryptedData:
    userID: AgCRdzjVYU5DS7LabyklD91L35S4W3QZz1vlQsD5Y24jtO2p1Fkj+RHfilq6hyCpn9CYZziXJWLX+wjLULiYNAq7pLxMZMKEWOiXoh92sEaygugbe3CWMykiXx3NjyNNnBcNsPHHvxanb5Cp+waQmIMg8pRgpjnwjLuBfxw2+tVQa8Qc0gwVKrYCfYGhfm011rqvo1ZbN2ipsxzyxVihiusnHAo3JJcXZ7ndUq4NFAxazuSugWlrNlzCKbtOPu2NAroXf7Ib613kdNU9oewbExqJ+JlQaZmVDMf9We0v2ITV7rgwczB2sbvRUNLZtljklTjhD0uSjApiIJh+JxBn1QNxTjEziJnwccv+SqIQNYSNoG72MXFfF0ALxSBidQZc4TMLaPP5VK5DDCzlIPiY9S1UNJoJlQIVwKgFReM58GLPxC9U1KTRN50+vCuJfERnJqdqs3vZa8qESAcC61fTePrhQLkEtRyz3nPptf7iXx2O1fvYQWFUuRrypf8/Su5O5a1EPEO6iJdYIhTDNrFKFwywfSFbeGpnkJrYRKoFp17ODmxLJDs0BekJuF12CzoWq2Z5MgkfM3Uoooa9H/myHTpTxjRUgKHM4I4sUDgd6Om+N+q8aJg0E1D5w18wriiemR3VJryErKq/zGKqiIxHj531TfpFtX9xCiDxNFUTaof7GR/eweTBaifNRabqAy49GajFL2Vszw==
    userKey: AgBKK28E1Zu/CfhRNOcay3P/FknDdgYaUbe29qYKuhmKN5BRkYX0Hru1AhwJtOn7O2+LPE3F122/cRlz6ePIvsx/1Q5di9Zr5CQOp7RL1v9OWpsRqFfGF30PC8I5GWsCkQPkz0S4WEEXMXqcKOjUenKjZ4k/9XuUYQ9ml6DJzaryJQToq7br3fuZ9RbaqX4wow/nZapVYuz70zINK5W/TjvRHXMBYih7Vq9ELWdbtTQNlBTC47C8YlpAp0EVsXC9nvhctbFVSbWgDvoZNPILHcCLogbxsM76L6P/ga/81lQxJ/53fJ3vxUo8IWhR3h8LKI+3mLg2ZwQLu9WMZq3PBojUpP7uhqmsGtSnANPykIYW3IIZqd4Twn0qdn90oQKiE4ikChz4r+5rW6SFP/PQU9IboOi5/fSY0ZOeXEdlgW8rYbMDGtfudRrSpg8cEydNAD+CMGwwAj7+5E2mmsuUOCd7H3ZidmmVeRe0P7SfSHSnjg/tS0zkZAnfkNMYgsT1FlgKHGRCOYckTfLulaSk4PrdXyAQK+B/AjDvLmcJeYXK2bE4SlEG6i5vKCjEfhpYTtXQdqY3EfOwBB3ndJ+dJRyQzgdDTIqmx3Np1HYEjlRmF0kjRMtIYm/acbRdb2qWlhjoKIjDdWG7a7YjhdA0yb3DDROpM+2Vljv6Rt0ebBRSAXv+FFWXe6U0AhNcG/AbnDmQVNwS4JR0QZepzAfhjKtru9ljtkJjM38U59xq1ohMVd/67Xh1lMss
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: storage

