apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
spec:
  project: infra-project
  source:
    chart: thanos
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.3.0
    helm:
      releaseName: thanos
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
