image:
  # -- image repository
  repository: ghcr.io/k8s-at-home/plex
  # -- image tag
  tag: v1.24.1.4931-1a38e63c6
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [plex docs](https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/) for more details.
# **NOTE:** Plex preference options are camelCase and CASE SENSITIVE!
# You can do horrible things to your Plex configuration if you are not careful
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/Chicago
  # ADVERTISE_IP:
  # ALLOWED_NETWORKS:
  # PLEX_CLAIM:
  PLEX_PREFERENCE_1: "FriendlyName=pleximus-prime"
  PLEX_PREFERENCE_2: "EnableIPv6=0"
  PLEX_PREFERENCE_3: "TrancoderTempDirectory=/dev/shm"
  # PLEX_PREFERENCE_3: "logDebug=0"
  PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
  # PLEX_PREFERENCE_5: "LanNetworksBandwidth=xxx.xxx.xxx.0/18\,xxx.xxx.xxx.0/24\,xxx.xxx.xxx.0/24"
  # PLEX_PREFERENCE_6: "TranscoderQuality=2"
  PLEX_PREFERENCE_7: "TreatWanIpAsLocal=1"
  # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    primary: true
    ports:
      http:
        port: 32400
  dnla-tcp:
    enabled: false
    type: NodePort
    ports:
      dnla-tcp:
        enabled: true
        port: 32469
        protocol: TCP
        targetPort: 32469
    externalTrafficPolicy: Local
  dnla-udp:
    enabled: false
    type: NodePort
    ports:
      dnla-udp:
        enabled: true
        port: 1900
        protocol: TCP
        targetPort: 1900
    externalTrafficPolicy: Local

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Enable devices to be discoverable
hostNetwork: true

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    mountPath: /config
    size: 20Gi
  media:
    enabled: true
    type: pvc
    existingClaim: "nfs-media-pvc"
    mountPath: /media
  transcode:
    enabled: false
    type: hostPath
    hostPath: /dev/shm
    mountPath: /dev/shm

# -- Configure the Security Context for the Pod
podSecurityContext:
  # runAsUser: 568
  # runAsGroup: 568
  # fsGroup: 568
  supplementalGroups:
    - 44
    - 109

# -- Configure the resource requests and/or limits for the Pod
resources:
  requests:
    #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    gpu.intel.com/i915: 1
    cpu: 800m
    memory: 1Gi
