apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: influxdb-tls-mapping
  namespace: observability
spec:
  hostname: "influxdb.twistedlife.space"
  prefix: /
  service: http://influxdb:8086
  allow_upgrade:
    - websocket
