apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-external-provisioner
  namespace: argocd
spec:
  project: infra-project
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner
    targetRevision: 4.0.14
    helm:
      releaseName: nfs-subdir-external-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
