values:
  image:
    repository: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner
    tag: v4.0.2
  nfs:
    server: "truenas.storage.twistedlife.space"
    path: "/mnt/Media/media"
  storageClass:
    defaultClass: false
