apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: loki-s3-values
  namespace: observability
spec:
  encryptedData:
    s3: AgB4hkJfA5d5TivabNh0HtYkGL5Lm0/jhmFsv/jgt2IOy/YdTltYXaJm+EudZ45n7Emh+I3XJX+/ilfSu8UgXU4VjenMKu/8iDy9/gRZmKPGAhbSuCtc04DvYQdftd4MDLfrTFPw2LbTUw+wAko+Q3YGdYZE5A4eosD1XaNEhZOQQgzCdteNQXWuUhx52IxlHyRDWSorBcnhAtL04nLVseQAPLVDDlt+JGfMopktCeX8BjB3lVWVX6ceY9gEJKK53XAXkMfSk5CH4a0TP7YbTnZca3J35TuP2T41h6c7E/pVyTXZrkXkgZpMJ2mJEKRnzKJL3UrrV9RFrK2ftdlLCQgJe25gbu1y+ICssshO4zZtOqrLUcvMGZghuHE8mcGt5TZK+RMMIsdC7SiJ1Xx4nXT7M8W3P/6nzV2vUfn3XswueaOYpZ1DQkwWTwrPhnFhR4+l95uS/4Xry4guBWCPajpVNt+wqfQKfbhNq1LfFf2qqUImzjk6EHq848XzvJivpJi4mx0agO8lQmceKuVyhntzqu/5Q9jVWpUd2BM5c4Zje2g1CmDDlY78w6JVPjjon9rFtyZvKckvqgAWRgP//rwuQV4WzKZNV68b2dlwUeaqylkTUsWw7C0G+5GlEEgyEIW06F5YaukQO3PGc88+jQlWXcXfWVkPD0LTG56APeg2dTOOQHI6Q53X6Psy23lwhUiXIlf+tZ4r2h9Y0SqrIJBxPA9H1OeOn3FWpYgGLNgrREMAhdalVp3ph3c0lfLgWuVMiWQD
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: loki-s3-values
      namespace: observability

