apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: loki-s3-values
  namespace: loki
spec:
  encryptedData:
    s3: AgCwTgY7OY6BboWFoDHGJlevS07b/ScIKtSNBYpqmoPxzlQFrqSH7cK18aiXGTDf0rrUw2b2rh942FmQCM4SibJbSIgccPIyTvEtJaQeAsJfOqZkbZQYDKKq6NT2Kz0FPLWq+1JshmrflWDn9SDQpUxSLiKiYJNuL0bSEslGWloZ6FnaiPCXAf0QjQ60t2qqway107wW+r90if7WGsBnfbt5Xl698ujTqg4Vqv0l9tx0hCXPGZM18jzf8i/rDdhmflLxnGV61dgDqhA7boOdPab6NJatidyF/LAuc9LEZbh3RSadWCGZLwOqdWjziHwKXx5VUsDb3MaTwHtYm0dI3+J0GmyxfCGq2/I230ZCm2456MUeKNOILJchrckfqEVk7P6vLGJPEk98Mdv6/FHl/vuP+diGf1RORCSRitEBIRTj3AH6J+BuTCfx/gGcqEK3AmpdhVf55D612cGg1P28uPGYhGNw7vxRpzEWzMp40U7SmkjxI4I7T8Q0I/dBNqZpmhiafomJ1owzYfa50/Wa8y+3clgothKqop7GJaO3573o6eY6ug0g7IJruaFud9A3Z8HvLXQdghwka8l+NallKnJV3SxEXiCNw5VGAoQogHDI1dQS+He17KeVEt2wdrGTAHasxslHi8VcxsY/fW1dSlefC7cWdbBLhbVX5zA8Ogb8YyC1dexCGL8KjkvEcag/+idXRgMD09tHm/z5c2LmoH24KEUT87Gc7MN3DDmxTNNLn6T1h1FXE8oxvmqMPR4iw5Y4Y6K8
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: loki-s3-values
      namespace: loki

