apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: loki-helm-values
  namespace: observability
spec:
  encryptedData:
    values.yaml: AgCeqRc4iznDU0MigsI2SojlwQW7tqcJTTdmab6RAw/UQVGR/g2cd44dabMF/zlBkHnYc+u8co1CyB/Tw6fIwdcfSeKJbShqhlZPKzl24qE753Mi5vAm4E8HUreJjLTDmHCghdUsIGwi1v1X/OhMMUrIPtY0tMecVGVcnQ5SqPcRqrZFNe2+CxieQjuZC6FKVr0slkIfdjLXppcJvP1ugIlMdpfCAAtsfwAtW0O5ZC4DjGeTcrR8JIjsv3yT3N4kM+ZXe19qcZ6/pMK37obi52WOtpXtA6wFBxyNFKS/2mKPFYqKJIXO2ODyL9JiUNcKA2vZCZmNItPWEYm5HzdNkjOsjHoUyo7vGV6Pa1uj9HHbgMwqYq1VKlWzBMadGylnf2HQU091xrc+3m2zo3/pBFypK04sxLbfbqYdIWptezkOQsJBJBAxd10L3mNea96NKYQfXzjvMCWZp/BjsPnK0gRqYFILzv/tVp3y/zFsUq5Y6cn4ABYdnouRp8vazPhO/fUC7QfkzhZ5eNhRiUNmEFOl/rzcJwagA9faJipNx3Lt4zQczenN3erixSQiau2PG0ULq/i3pjTRSila4xuDSRaM3MJcoDEb0WbSANyb4rD0FD/3rxPIj4VY+NMvnGCl1r22zvTnziHECJ8sEVB0hHFGC82BogI6c4GndAYvw9b/0eW+wdAB3II3G/iIll0J6tyMV4DC5OYIq5sMQxbQJL6nVK5dqw4Wnxr4TiD4qlgznBrnN+DIn6qjSMNfEi0S9pQ5VNtob4wP56zZ4OsVPbJ0HP01GcHqWzzD0f7Wy8Ft2+e/OAuVbqdylrN6H1GBwd7DqS/91BDaZ4U4aAtsBU/SOLN9JetW9ZAH6/Gf6sAFuvMfv3V9MenWx2rH5hFe2DEg0I9R8hFk10ZwatSNYXb+tYrsnzAXSp42Eh9jAugWT74MhfJYkGjCju82YW61kNn4U315lBtIZNEKamnAU9u2WtbMDxeop5pBVcAxXMjM+xJ6aGs7NYVvCcEHNKEQ/mXzK6LwnfVr
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: loki-helm-values
      namespace: observability
