apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: loki-helm-values
  namespace: loki
spec:
  encryptedData:
    values.yaml: AgDJbKEanyZ/cpGxosJyifz3ukaIzYI+hsC0/gmu7L2k5SQ8OtGfsUv0NUmoTbvSjodHpou8oDZVkpoXeQ1CQzWBaSkTfEvL1fP4QlDSXSNh9RlFDXYDsI2FZ3dqzc92km3bbebZ2oEVrUT+x+FvnUXHOURGM2todziYZHsj1XfW/KUzaRhRsy6jIAcOn87tVUTCbPe6FyzlX0N4/K5ex61pxZUKxh8rC0myiFyoOySc0zwlcvCP/zTvbrEkx+BycFVwR2h3yjnDd/FmW+tLMJzhE8xb69eGtNUuwdyf9kJBzt2PVUNQ3Bci0O1xs0vPJwuoV+uZhf0KbZdtj9HqHDGqcKJ6NhlZGMkJkCPjjKWhqs9/RKAtLdOZlmRMlsVadp5VJo0G4Gqj22r55b63WnXEjGm50Cwx/wgrCiYxmSoUnjQiVuHKcQKQotu8aBxvP+Sienl3CcRf9PRDmty+udsIYequXzCbhcqcPU8kq5mcEJ77vJbxWcZ0jHYCaDOGpLEpVV6fFF9+pT36DKxFZi2iMReGgrNmFCb2k0N863jQ3cu5j1gh1SOqBYpzSZC/MP1n8LzCH+To6BnL3NccFG5FVpT/Wz6jrGbXjhyx5Wf7VcpuIn3wqq5KG+WiLUwTkX6Z7axC29zLtm8brViaErGl/LsSh0jEkFJoNi48knvBEzZV3Coc5988zb7FNS4t/MgBkEjK59U7nHwnkWqeJigeAeLuwYeZZaz8K/SEghI+eMB0wTWdnqtWOgIySmAEuaqpK7vevP3jE9YJzMqNXCBIqhk7xVFO3qLk75bPyAxiqKEYeBZmtsFUv1eFssbkWMV5cwMJZJpHRwPqRb6wWXNCtJTZ3stwDwAYRuL4BFdHs/rqL12sMbBE5vCKf4hE/n7lueuJef9P1DgbDENcGQ6vT6H2lTlB/jiSYp5Jqpg+yZVdC1oMPabFuEoC42WexduFRto71HoAacl2VZaoShPChJQVnjvoLnVmo8qY2egwP3LiFvLgyPvYDI9BATKIj9pCCPfzUE2s
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: loki-helm-values
      namespace: loki
