apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: thanos-helm-values
  namespace: observability
spec:
  encryptedData:
    values.yaml: AgBVmUg4urHFXAsNEotTImyIYfCVMnmR+xHFb1Sql4VLMniNSG5ftijOWSi0ehQhLwi2TclYaVpGPQM8iCprH+/qa6ls8fLByVDDIjzyI3COzB+EFHdPl71Cud5uy5L+ZPetZgVR1FO6fCNTGsgGlM4mR35OKmNkbD2YGTX2dvIiQKBGvII6+x76j0zXWrxdEgmkRsDgbVGwvaqhUyZoPWZd3+2u/Fr1LH4dD2NQsKQ8xp9Jn4w2N4eapCLMOZvhbD+d078ysLq0vVWWHHVVyvQKYsUwj5YWZXAOs1AhSZsrGvgEEILhnRCRrryFaVsVKdsskCitKGx9DENiJpvsF3xk6VN6hb2zwRWZyayMv2GSX5JqY/RehQWIpuSp+83fAmauAZRO1YyoHSS7l6HSkE9wJo494o4TJMauZ4pfMV6OZpJuYMTUdEn+cAwqsoRxFLWls9rVX/h9qpR3ex2JUfvaJJ8WeKnJAQmw7bEpVhfchHyQnpk9NJeDUW94TQvsxtM0va6a3eqmE1XcNxFnfgsPkIJS2IS5ffT0I3FZYklmatgg1ngjG+cYC8aVqGLLHmu5cG5jrfV0pjMmbtBz/G1DsQKaELEeXqGNNPQ85pWKO5G8uIg9+yjwRfiN/kyRV1FKZHL6JcKrEz3agBgjNQmNlebRa5VBufeL9hfPlT4M+M5W82t0Pj1+GRSpR5rnTxnG5j9Lo2gRz8DHLUtEFpVKWW+A0XM0LwmMbCRJvTWU2DfXCKsUgHWb4GvIY9CSsbidao7syaIr1C+q/w2mUaP7u0rLzVcMloIORHs=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: thanos-helm-values
      namespace: observability
