thanos:
  query:
    dnsDiscovery:
      sidecarsService: kube-prometheus-prometheus-thanos
      sidecarsNamespace: observability
    replicaCount: 2
    replicaLabels:
      - replica
  compact:
    retentionResolution1h: 5y
  objstore:
    type: S3
    config:
      bucket: "thanos"
      endpoint: "s3.twistedlife.space:9000"
      access_key: minioS3
      secret_ket: minioS3S3 #testing :P
      region: ""
      insecure: true
      signature_version2: false
      put_user_metadata: {}
      http_config:
        idle_conn_timeout: 0s
        response_header_timeout: 0s
        insecure_skip_verify: true
      trace:
        enable: false
      part_size: 0
  ruler:
    enabled: true
    alertmanagers:
      - http://kube-prometheus-alertmanager:9093
    config: |-
      groups:
        - name: "metamonitoring"
          rules:
            - alert: "PrometheusDown"
              expr: absent(up{prometheus="observability/kube-prometheus"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
