apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: thanos-tls-mapping
  namespace: observability
spec:
  hostname: "thanos.twistedlife.space"
  prefix: /
  service: http://thanos-query-frontend:9090
  resolver: endpoint
  allow_upgrade:
    - websocket
