apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: thanos-objstore-secret
  namespace: observability
spec:
  encryptedData:
    secret.yaml: AgBBo9dgcnycYNTo5GyWMlnMakXy25tiZnCOdUTgARBhyVnvA1GC/vX3464vnw7iqfAj+RAh2Udkg37Tc6Lf6g841DTgD/DK3sqF1KQaW56+VM1oLU5kZ60A123p+MVAqN6jOX9FlvFrAQg21eB6YtLle+qbdHnHWrODUkutehTKyNOyzxvEB0P3DxWne+V2PRkQ1xwFpQoSMxx6jIZy8AyY6BEaxRbD9fcwluTsQYNZYKhNpeKFv8opl3vJR6tiYbMuloHk+Z/HAHl/Ap9kC+AG4ApjTG1rJw/JfutjgtpHAv6T438TL/eA54GYjxlSHK4K2BVnU/jSd78ZHklCaq+CBn+r4FUCoqIbJYwhPLbBWv4qqMJGWuFxbzMEAOuMg7v01FxxlkWHtNCsxQ4S3+cD5k2Rq7sKS/eyDNafZQa0lcxBlTiTDJn3PiLZJC5BXjFeSh3Ka6A9ExzuUz7GuLbi53hv6xBJwnv7q0+D4j82lQ3LzzifZG9k7bFZLscdC8AKxqzzQvtxWDwh7Up7CEf2m4UDqsxkMD42kwrlnjHdCtafaEHrYhkF13bdJ4QYaB0nrbqZcDw9ITX+z3Hdgy726v+y/nnubV9D8UuygFSnqhW9SoVY202j/WTNH9663RfxX3FDD/Zg7b/Cr7OggioC4v248+HfA8i4pN3ACiu2bAWTt81GSWJ0lzmZWMmOH4wJUcOg880Xn9S78dobNq7SgmbEl3pRRfMbfhHx+RoJWPTCO18Zv5Vdu/oXwhKZ7XfVV0GfaUxqfhHqOCxXVuIwCQOZ3F9YbsmsdzED8RtYvXf8YA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: thanos-objstore-secret
      namespace: observability

