apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: thanos-objstore-secret
  namespace: observability
spec:
  encryptedData:
    objstore.yaml: AgDJAzcl5shflMoT9n2LARN9y8ytUWpv4gY1wlOE1Q/TKNn6mblfg/DVPIyYFDzzArHS69GKFoPR6pyd5aNCob+tO97keJTOwuoEeILK5TfjWs6Gm3WYFNZkkRsxByFHqenR3GieR11FE7VJvchEo3mfLZa3/fA9i/749Sq6v70cO0VkGRcE/o5jmryd70tSDWPas6TvG1fgekJhpoCdh19rZj2H0JrYb/pTOo4ANycRFUjwP51VHpT1PN00j1i9cBjfPxVMSppyhJSm8GFtIr3EjZjpd01Fx4m6MGGd+wCiBp3OQXMGIapFyiGHN9D97faCgLO6MAXwMHE+f/TjFFD+r9ejpLQXB97xNYOI8g9jb68kZ4IeyEh8BqKVknorMrFuzah4QhjpqE9dR3fCRSjobr/4eHI4mIBRNYcWOjj9jVO14STKeEHWhxmZXt8WYwGRHSVHiMfytAhOZNzkakQQ7m/zpDIOICNpkSG9Y0aLTrr+A4LAwctgF2QEHN1bUC8f0Hg1sSMJMN+Vb/ZVtsKpaEOV5b75OujbGap6S13aKjSIG44bkE4msHDjSPI++7omb888QUZd81vW82/9rQThgRRB3W+SIZ6AMPVIGtSvANlvjHCiUk5aoAvnlLqXROAIuzpfujS9kFlbuvMdo+LB+J/IsdsIhbrP1WN4xcMJlqKAXAum+KTlS1ZNCzO2IjCdzrrrkhXz9rmPz7E3DfCigiKkzIxLfN6xfzmWMrMXMVAHEYeJNoxlr/Qp4CnhFFxht+3weqoB/mQydGfDNp21fpk279+65t/VaCE=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: thanos-objstore-secret
      namespace: observability

