apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: thanos-objstore-config
  namespace: observability
spec:
  encryptedData:
    objstore.yml: AgBNORQvoLMgMkjPGyfNNlq3jrGlFmNONFq/yXSO5yBHHEvwy0iyibZeWmZObQiRgMcUCK7VYKzg6W0ZsomnlFYOf7I0SVATaIG3lGpgq9eB+C8hvDFp8r0lr7dZ8kTbqRVHv5Iav+Nr46lWBNMZeV8edNCev1rDBxQOE9xJLIxJs+1DX2SW0Z4h2Xtaw2feWjNsdV3FvC8WUqoKCJsv5xKphBZzKMaUenV9jaoYUe2NuNLi4VBe9shxKm+LMV6tqz0ExoLqngehRp3SImq8zt3CbWCG36FEM0uGA1zk2NXhlZmpI9ahfLjdny5SfQS3I0A5R469QHrnp9ACmOGxUMEEz3T+8YAgrdFWb1kSBbNASzCsriyYoke/S3Iiso95VAdbWHr0C7r0HWpBadOZvwOTV8qklA55VEzrNx2Dl9VjSLZlJW+INTwtM7kQaQwu9ldsOsBH9svBgOluJ9CHEUxvCpEPCMhY7zQ0f1V1lK2LoQ5YMxxxT/OsWtSYBGLEIU1FcXXYsmvHOirXNy+NfjPsECR3utVEpqulUny38uscF8SutOLiGtEkKh10bLFA2OJZnnl2uXRbSXH2V6YjzMSSO/vl58aR1RRHppVTPhLq1+zKBl9p0dQhMk1qbHe8ibhLBdSk9pNps60ALO36huFZ0w4NnuRgx1KV8TDNB8vBWMsqdyLsjwIm6aE9d2ZziFiNB4WWeecClcXrEg0G33nhAi1muY6uirz/qhuASgvQ/Qla3wuKmLmpX3KFtCDud1MZLCkhT00yYe6esIYSCp4trJY7a/TutW2XC+xVMskEUqA06z3l+OVUsSpHLMkAIp7FtTYJPltmJP6rB6ebWzw7GFBwUyK3Nhqo9CcDheU6AxR2XRN9pXAFqDHEpbrbZzBwK4VAw4ZbBDYdCP0gtLkfwPf11mDe6BQ94o+KmB4VUG309iFWZLUxTS7e6npDFKP0hzDppf1dUgVrvgdcgy0fnsYfiSoftCCnMzdXLvUWqvwtv2IqT0b77EISNd88N3S/+5KmKBsE7iXBl1iCesDDWupuCGskGcn4MrOYpevxxwdtX8xsB5Bmy8UqyErk8b5ULp7fbBwVukOOSEUTefHezEdcKNyRSComREMN8x1BL24MR4vLhMoewfDBZBajM8Tch2u5
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: thanos-objstore-config
      namespace: observability

