apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: thanos-objstore-secret
  namespace: observability
spec:
  encryptedData:
    objstore.yml: AgAf1obeD2GL5x34c2L5kvR++lAQu1dhM3uRrHxDr0Ys14tFZPKYGcqpdBip1n9mrjZW7A+ch8dhYuBNSoVUxBTgy9ZYkJHrr6a3ElCiLN3BtiIvYsCi+RqSSubl2Hw0kQXN7gftPyuwK/KrqVTJFKzxJB99j28QoJWORq4PGCWvmn8hqe+93Xr0Zr9amk81y/Nfrbx8KGii5zvxBqUIYbHlOYFjWfu0MYT6XrbvlzlpH24Z3VcGZ8qYGnquYrGH3QMEbju9x+ZEQ54g+F+lcOiDbbtaj0enJPsy4XtV2qyUoEla1ptCec/uKDV46zv/TGDoXpkMRMlQpiJ56oD8rZxF6NPqqZ2ELxvGX/ojnTbtVif69bauvBBwNJKCmOlZgdQLGn0B5wMtzK675qX7no8DPd+FRr4wC8UEBkwYaU9s9/wYGLApQqAQFdwonxlpZFy2yxTuZT+32GyU2VvtGAIxKSAT1gueyKkxPnCbuPKvkxBCajuV/OqbtRRaXLpdy4Joj2w+pLEfF2AnpLdd+TZL1Q/NIuxkISj92XXuu2Hc8e/Dg516Yc1j+hIRoZxrzOOAcGp+oVfmfioqfEg/+Fw7g3KD21y+Lg5kffCBvRrryQTZ8apqnVx0P1NxVe74xNzfwlIcgPhLiZje5LX4aLaBusz+MMpNRB4gW/MHZZN9SqFm2gME4fbbx5L4FyPLMhxlvfPiFc3ijtwfmrca0mbA+7qMgAYd7t5+Wh9GVWRfBnTE7mheAtju9xwS8kdZoS9nGc83li+auDiO/OCVHQKTQtDVHEQxBIbGP5wJMugjjo6xeQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: thanos-objstore-secret
      namespace: observability

