apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: thanos-objstore-config
  namespace: observability
spec:
  encryptedData:
    objstore.yml: AgAEuQLAYYcwFntKbIzjpZPRGVxEfytE0FGL2eizuQ9k3WLjBSwSEnZmco4S9srvwvosVcmtY9Jo2+ppBkQ2qcRXxPTIMbeB0+fn9UxYZeS+9MBtXQVTumJAH+oQM2pF72uuD/vFYoc/5zE89wqiG6E5MC95QMDdouMixyLNgIe6QC0aJ1LQWOwcH+kdPKg5T5N7rBU64WmrK6+1dHg5izDqEAHkodmasyfkXfXkH15qhtt4jOMNimAfpoqfqH/uWuQW+5amwPQmdnIAGYsdlAgyiTl5D80r6rOzDzXfPfpuZKgkJsD4pU0yxObqVTSvF7SbzfOOLI2615869pIJ8g+HVYP9m/feRnMhaeNNL5ZCW09qQhuygIAZmg/GkCZX67lTQBnb3qhrwbFmkwi6FXIUf4kN+mJYDP4v+G8xk5k4OdXf26CBuU1iU1hchRf4frmef3Ft9TlKcJB2kgJVGHgkU9oykicDiBVayGKr5Ejvfa5ORGnmkaVBN+TdyPHHIpHJUEs9f/PJPM1dOhHjPSmnhLSgznm3Mx4sELyeW54GUrRjyvnN4ka60mCfRKhmhgon1h7c7vgIN1mQ0m0GkR8dpzz3iNLQG7gbYiORyS3tv4o0td9NQIcxbOhDXUrLuubwTidDN1WtJLLFDSqtxOFKKEUzmt4hpaW6PAjO7wfbKCbDpjsF4siL3msb9h15v74diKHReyBdY0iAs7voLVXtOVXJpO6deUSkEP1ccMX3EiIJb6dTqKvQrJL563JExm58AOWbEOcsMuTuQh47uQJf+/nl/4bjE99PPSkCaAzz19kuN6hazXIdG3SflqYwzKg+IEE8W1ffy14G5FOJZHXBnHUz
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: thanos-objstore-config
      namespace: observability

