apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: yorkhaus-infra
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    helm:
      valuesFiles: values.yaml
    chart: kube-prometheus-stack
    version: 30.0.1
    repoURL: https://prometheus-community.github.io/helm-charts
