apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for Kubernetes
type: application

version: 0.1.0

appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: 27.0.1
    repository: https://prometheus-community.github.io/helm-charts

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: loki
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    helm:
      valuesFiles: values.yaml
      # renovate: registryUrl=https://grafana.github.io/helm-charts
    chart: loki-stack
    version: 2.6.0
    repoURL: https://prometheus-community.github.io/helm-charts
