apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
spec:
  config:
    gzip:
      memory_level: 7
      min_content_length: 32
      compression_level: BEST
      compression_strategy: RLE
      content_type:
        - application/javascript
        - application/json
        - text/plain
        - image/svg+xml
      disable_on_etag_header: false
      remove_accept_encoding_header: false
