apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: storage
    name: in-cluster
  project: twisted-infra-app
  source:
    path: app_base/storage
    repoURL: https://github.com/dsyorkd/yorkhaus-infra.git
    targetRevision: HEAD
